services:
  practice.api:
    image: ${DOCKER_REGISTRY-}practiceapi
    build:
      context: .
      dockerfile: WebApp-Kubernetes/Dockerfile
    environment:
      - DEPARTMENT_NAME
      - COMPANY_NAME
      - LOCATION
    ports:
      - "8080:8080"
