apiVersion: v1
kind: Service
metadata:
 name: practiceapi-service
 namespace: backend
spec:
 selector:
  app: practiceapi
 ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
 type: LoadBalancer