name: CI/CD - Deploy to Vultr Kubernetes

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: indar25/practiceapi
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f WebApp-Kubernetes/Dockerfile .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Load Vultr kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.VULTR_KUBECONFIG }}" > ~/.kube/config
        
    - name: Create Namespace
      run: kubectl create namespace backend || echo "Namespace already exists"
    
    - name: Replace image tag in deployment.yaml
      run: |
        sed -i "s|image:.*|image: $IMAGE_NAME:$IMAGE_TAG|" k8s/deployment.yml

    - name: Apply ConfigMap
      run: kubectl apply -f k8s/configmap.yml

    - name: Apply Deployment
      run: kubectl apply -f k8s/deployment.yml

    - name: Apply Service
      run: kubectl apply -f k8s/service.yml

